verbatim:
  cabal-version: 2.2

name: duet-sgx
version: 0.0.0.0

default-extensions:
  - ConstraintKinds
  - DataKinds
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MonadComprehensions
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - QuantifiedConstraints
  - RankNTypes
  - RebindableSyntax
  - ScopedTypeVariables
  - StandaloneDeriving
  - Strict
  - StrictData
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances
  - UndecidableSuperClasses
  - UnicodeSyntax
  - ViewPatterns

ghc-options:
  - -Wall
  - -Wno-orphans
  - -Wno-partial-type-signatures
  - -j
  - -rtsopts
  - -static

cc-options:
  - -static

ld-options:
  - -static

executable:
  source-dirs: src
  main: Main.hs
  dependencies:
    - base
    - base64-bytestring
    - bytestring
    - cryptonite
    - cryptostore == 0.2.0.0
    - directory
    - duet
    - memory
    - normaldistribution >= 1.1.0.3
    - text
    - uvmhs
    - x509
    # - random
    # - mwc-random
    # - time
    # - normaldistribution >= 1.1.0.3
    # - memory
    # - bytestring
    # - cryptonite
    # - base64-bytestring
    # - directory
